#include "config.hpp"

// XXX: to be generated by build script

namespace brfc {

const char* test_schema_dir = "/home/snny/src/baltrad-db/schema";
const char* test_dsns[BRFC_TEST_DSN_COUNT] = {
    "postgresql://baltrad:baltrad@localhost/baltrad"
};

} // namespace brfc
