#ifndef BRFC_TEST_CONFIG_HPP
#define BRFC_TEST_CONFIG_HPP

//XXX: to be generated by build script

namespace brfc {

#define BRFC_TEST_DSN_COUNT 1

extern const char* test_schema_dir;
extern const char* test_dsns[BRFC_TEST_DSN_COUNT];

} // namespace brfc

#endif // BRFC_TEST_CONFIG_HPP
