Import("env")

sources = env.Glob("*.cpp")

env.Append(CCFLAGS=["-g", "-DBOOST_TEST_DYN_LINK"])

if env.get("test_db_dsn"):
    env.Append(CCFLAGS=("-DBRFC_TEST_DB_DSN=\\\"%s\\\"" % env["test_db_dsn"]))

env.Program("#test/runner", sources,
            LIBS=["gtest", "brfc", "hlhdf"])
# vim:filetype=python:et:ts=4:sw=4:
