# Copyright 2010 Estonian Meteorological and Hydrological Institute
# 
# This file is part of baltrad-db.
# 
# baltrad-db is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# baltrad-db is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public License
# along with baltrad-db.  If not, see <http://www.gnu.org/licenses/>.

Import("env")

classpath = [
    env.File("#lib/jbrfc.jar").abspath,
    env.Dir("#deplib").File("junit4.jar").abspath,
]

java =Java(target="classes", source="eu", JAVACLASSPATH=classpath)

env.Depends(java, env.Alias("java-wrapper"))

build_dir = env.Dir(".").get_abspath()
jar = Jar(target="#lib/jbrfc_test.jar", source="classes/eu",
          JARCHDIR=env.Dir(".").abspath + "/classes")

env.Alias("javatest", jar)

# vim:filetype=python:et:ts=4:sw=4:
