Import("env")

sources = [
    "exceptions.cpp",
    "DefaultFileNamer.cpp",
    "FileCatalog.cpp",
    "FileNamer.cpp",
    "Query.cpp",
    "ResultSet.cpp",
    "Variant.cpp",
    "expr/AttrReplace.cpp",
    "expr/Compiler.cpp",
    "expr/Expression.cpp",
    "expr/Factory.cpp",
    "expr/FromClause.cpp",
    "expr/Join.cpp",
    "expr/Select.cpp",
    "expr/Selectable.cpp",
    "expr/Visitor.cpp",
    "oh5/hlhdf.cpp",
    "oh5/Attribute.cpp",
    "oh5/AttributeGroup.cpp",
    "oh5/AttributeSpecs.cpp",
    "oh5/Converter.cpp",
    "oh5/Group.cpp",
    "oh5/File.cpp",
    "oh5/FileLoader.cpp",
    "oh5/DataGroup.cpp",
    "oh5/DataSet.cpp",
    "oh5/DataSetGroup.cpp",
    "oh5/QualityGroup.cpp",
    "oh5/Node.cpp",
    "oh5/RootGroup.cpp",
    "oh5/Source.cpp",
    "oh5/SplitPath.cpp",
    "oh5/SourceCentre.cpp",
    "oh5/SourceRadar.cpp",
    "rdb/AttributeMapper.cpp",
    "rdb/RelationalDatabase.cpp",
    "rdb/RelationalResultSet.cpp",
    "test/TempDir.cpp",
    "test/TempH5File.cpp",
    "test/TestRDB.cpp",
    "test/TestSwig.cpp",
]

confdeps = env.ConfHas("#shared-library-confdeps",
                       ["qt", "qtsql", "hlhdf", "boost"])

objects = env.SharedObject(sources)
env.Requires(objects, confdeps)

lib = env.SharedLibrary("#lib/brfc", objects, LIBS=["hdf5", "hlhdf", "QtSql"])

env.Alias("shared-library", lib)

env.Install("${install_root}/lib", lib)

# vim:filetype=python:et:ts=4:sw=4:
